import React from 'react';
import { StageFlowStatus, StatusMeta } from '../../types/design-system';

export const STATUS_CONFIG: Record<StageFlowStatus, StatusMeta> = {
  PENDING: {
    code: 'PENDING',
    label: 'Pending Queue',
    category: 'neutral',
    description: 'Awaiting scheduled batch cycle or preliminary intake validation.',
    operationalContext: 'No active automation running; item in queue.',
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-800',
    borderClass: 'border-amber-200',
    dotClass: 'bg-amber-500',
  },
  REQUIRES_CONFIRMATION: {
    code: 'REQUIRES_CONFIRMATION',
    label: 'Requires Human Approval',
    category: 'warning',
    description: 'AI recommended an action exceeding autonomous financial threshold; human sign-off needed.',
    operationalContext: 'Blocking pipeline gate. Requires licensed debt officer override.',
    bgClass: 'bg-indigo-50',
    textClass: 'text-indigo-800',
    borderClass: 'border-indigo-200',
    dotClass: 'bg-indigo-500 animate-pulse',
  },
  EXECUTING: {
    code: 'EXECUTING',
    label: 'Executing Transaction',
    category: 'active',
    description: 'Automation worker or payment gateway dispatch currently in progress.',
    operationalContext: 'Idempotency lock active. Do not interrupt.',
    bgClass: 'bg-blue-50',
    textClass: 'text-blue-800',
    borderClass: 'border-blue-200',
    dotClass: 'bg-blue-500 animate-ping',
  },
  VERIFYING: {
    code: 'VERIFYING',
    label: 'Verifying Settlement',
    category: 'active',
    description: 'Reconciling ledger hashes and counterparty bank response.',
    operationalContext: 'Awaiting clearinghouse settlement ACK.',
    bgClass: 'bg-sky-50',
    textClass: 'text-sky-800',
    borderClass: 'border-sky-200',
    dotClass: 'bg-sky-500 animate-pulse',
  },
  EXECUTED_VERIFIED: {
    code: 'EXECUTED_VERIFIED',
    label: 'Executed & Verified',
    category: 'success',
    description: 'Transaction settled, core banking ledger confirmed, immutable audit entry created.',
    operationalContext: 'Authoritative Ground Truth. Legally finalized.',
    bgClass: 'bg-emerald-600',
    textClass: 'text-white',
    borderClass: 'border-emerald-700',
    dotClass: 'bg-white',
  },
  EXECUTION_FAILED: {
    code: 'EXECUTION_FAILED',
    label: 'Execution Failed',
    category: 'danger',
    description: 'Gateway returned rejection, webhook timeout, or ledger discrepancy occurred.',
    operationalContext: 'Requires exception review or transaction retry with backoff.',
    bgClass: 'bg-rose-50',
    textClass: 'text-rose-800',
    borderClass: 'border-rose-200',
    dotClass: 'bg-rose-500',
  },
  REJECTED: {
    code: 'REJECTED',
    label: 'Proposal Rejected',
    category: 'danger',
    description: 'Human operator or compliance rule dismissed the proposed workflow adjustment.',
    operationalContext: 'Archived with dismissal reason. No automation triggered.',
    bgClass: 'bg-red-50',
    textClass: 'text-red-800',
    borderClass: 'border-red-200',
    dotClass: 'bg-red-500',
  },
  ADVISORY: {
    code: 'ADVISORY',
    label: 'AI Advisory Note',
    category: 'purple',
    description: 'Non-authoritative intelligence suggestion generated by collection optimization model.',
    operationalContext: 'Informational only; does not alter legal debt stage.',
    bgClass: 'bg-indigo-600',
    textClass: 'text-white',
    borderClass: 'border-indigo-700',
    dotClass: 'bg-white',
  },
  APPLIED: {
    code: 'APPLIED',
    label: 'Strategy Applied',
    category: 'neutral',
    description: 'Workflow policy active on debtor account (e.g. 14-day grace period, auto-SMS cadence).',
    operationalContext: 'Rule engine running according to schedule.',
    bgClass: 'bg-slate-900',
    textClass: 'text-white',
    borderClass: 'border-slate-900',
    dotClass: 'bg-sky-400',
  },
  OVERDUE: {
    code: 'OVERDUE',
    label: 'Past Due SLA',
    category: 'warning',
    description: 'Legal statute or debtor promised payment date has passed without settlement.',
    operationalContext: 'Escalation triggered. Priority queue repositioning.',
    bgClass: 'bg-orange-50',
    textClass: 'text-orange-800',
    borderClass: 'border-orange-200',
    dotClass: 'bg-orange-500 animate-pulse',
  },
  COMPLETED: {
    code: 'COMPLETED',
    label: 'Case Closed',
    category: 'success',
    description: 'Debt satisfied in full or formal settlement deed executed.',
    operationalContext: 'Closed status exported to credit bureaus.',
    bgClass: 'bg-teal-50',
    textClass: 'text-teal-800',
    borderClass: 'border-teal-200',
    dotClass: 'bg-teal-500',
  },
  ACTIVE: {
    code: 'ACTIVE',
    label: 'Active Placement',
    category: 'active',
    description: 'Account actively being serviced under primary collection stage.',
    operationalContext: 'Dialer, portal access, and correspondence active.',
    bgClass: 'bg-emerald-50',
    textClass: 'text-emerald-800',
    borderClass: 'border-emerald-200',
    dotClass: 'bg-emerald-500',
  },
  INACTIVE: {
    code: 'INACTIVE',
    label: 'Inactive / Dormant',
    category: 'slate',
    description: 'Collection paused due to dispute, bankruptcy stay, or legal recall.',
    operationalContext: 'All outbound communications hard-blocked by compliance.',
    bgClass: 'bg-slate-50',
    textClass: 'text-slate-600',
    borderClass: 'border-slate-200',
    dotClass: 'bg-slate-400',
  },
};

interface StatusPillProps {
  status: StageFlowStatus;
  size?: 'xs' | 'sm' | 'md';
  showDot?: boolean;
  showCode?: boolean;
  className?: string;
  onClick?: () => void;
}

export const StatusPill: React.FC<StatusPillProps> = ({
  status,
  size = 'sm',
  showDot = true,
  showCode = false,
  className = '',
  onClick,
}) => {
  const config = STATUS_CONFIG[status] || STATUS_CONFIG.PENDING;

  const sizeClasses = {
    xs: 'text-[10px] px-1.5 py-0.5 leading-none tracking-wider gap-1',
    sm: 'text-xs px-2 py-0.5 leading-snug tracking-wide gap-1.5',
    md: 'text-xs px-2.5 py-1 leading-normal font-medium tracking-wide gap-2',
  };

  const dotSize = {
    xs: 'w-1 h-1',
    sm: 'w-1.5 h-1.5',
    md: 'w-2 h-2',
  };

  return (
    <span
      onClick={onClick}
      className={`inline-flex items-center font-mono font-medium rounded border transition-colors whitespace-nowrap select-none ${config.bgClass} ${config.textClass} ${config.borderClass} ${sizeClasses[size]} ${onClick ? 'cursor-pointer hover:brightness-110' : ''} ${className}`}
      title={`${config.label} — ${config.description}`}
    >
      {showDot && (
        <span className={`rounded-full shrink-0 ${config.dotClass} ${dotSize[size]}`} />
      )}
      <span>{showCode ? config.code : config.label}</span>
    </span>
  );
};
